name: Build Test

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v3
        with:
          install: true
          cache: true

      - name: Install Tuist
        run: |
            mise install tuist
            mise use -g tuist@latest

      - name: Fetch Dependencies
        run: tuist install

      - name: Create Environment.xcconfig
        run: echo "${{ secrets.XCCONFIG_CONTENT }}" > iOS/App/Environment.xcconfig

      - name: Generate Project
        run: tuist generate --no-open

      - name: Build Project
        run: tuist build